import { H, VC, type GenericProcedure } from './types';

// Liquid-chromatography procedures (HPLC, UHPLC, PrepLC, LCMS, SFC, IC).
// Keys are normalised issue categories (see agents/ranking/families.ts).

const LC_SAFETY = [
  'Depressurise the system before opening fittings; UHPLC systems can exceed 1000 bar.',
  'Handle organic solvents and acidic modifiers in a ventilated area with eye protection.',
  'Quarantine results generated while the fault was present until root cause is confirmed.',
];

const LC_ESCALATION = [
  'Fault persists after the operator-level checks and actions below have been completed and documented.',
  'Leak, pressure or error-code alarms accompany the symptom.',
  'Any action requires opening pump heads, detector optics or high-pressure modules.',
];

export const LC_ISSUE_PROCEDURES: Record<string, GenericProcedure> = {
  'carryover': {
    key: 'carryover',
    title: 'Carryover in liquid chromatography',
    hypotheses: [
      H('Autosampler needle, needle seat or sample loop retaining analyte', 'high',
        'Inject the highest standard, then two consecutive blanks; then run a needle-wash-only cycle before a third blank.',
        'Peak in blank 1 that drops by more than 90% in blank 2 and disappears after the wash-only cycle.'),
      H('Needle wash solvent too weak or wash volume/time too short for the analyte', 'high',
        'Switch to a stronger wash (match analyte solubility: higher organic, or add acid/base) and repeat the blank test.',
        'Blank response falls in proportion to wash strength.'),
      H('Injection valve rotor seal or stator scratched or worn', 'medium',
        'Replace the rotor seal (or bypass the autosampler with a manual injection) and repeat the blank test.',
        'Carryover disappears after seal replacement or bypass.'),
      H('Adsorption on the column inlet frit or stationary phase', 'medium',
        'Replace the column with a zero-dead-volume union and inject a blank after the high standard.',
        'Carryover disappears without the column (column-related) or persists (autosampler-related).'),
      H('Adsorption on tubing, fittings or detector flow cell (PEEK or stainless surfaces)', 'low',
        'Run three extended blank gradients with the column removed and watch the decay of the residual peak.',
        'Slowly decaying signal across successive blanks that clears after a strong-solvent flush.'),
      H('Contaminated blank solvent, vial or mobile phase', 'low',
        'Prepare a fresh blank in a new vial with fresh mobile phase and inject before any standard.',
        'No peak in the fresh blank.'),
    ],
    checks: [
      'Confirm the peak in the blank has the same retention time on every detector (UV and MS together indicates chromatographic carryover, not MS source memory).',
      'Run blank, high standard, blank, blank and calculate carryover as blank area divided by standard area.',
      'Review the needle wash settings: solvent composition, volume, number of cycles and whether wash occurs before and after injection.',
      'Check vial caps and septa for coring; inspect the needle tip and needle seat for scoring or deposits.',
      'Inspect the injection valve for leaks or salt deposits and note its injection count since the last seal change.',
      'Perform the column-bypass blank test with a zero-dead-volume union.',
      'Check whether carryover scales with injection volume and sample concentration.',
      'Review recent maintenance or method changes that coincide with onset.',
    ],
    corrective_actions: [
      'Optimise the needle wash: stronger solvent, larger volume, longer time, dual-solvent wash if supported.',
      'Replace the needle and needle seat; clean or replace the sample loop.',
      'Replace the injection valve rotor seal and stator if scratched.',
      'Flush the flow path with a strong solvent sequence appropriate to the analyte, then re-equilibrate.',
      'Replace the guard column or column if the bypass test attributes carryover to it.',
      'Reduce injection volume or sample concentration and use fresh vials and caps.',
    ],
    verification_criteria: [
      VC('Carryover in blank after highest calibrator', '< 20% of LLOQ response (bioanalysis) or < 0.1% of standard area', 'Per method SOP', 'Inject highest standard followed by two blanks; integrate at the analyte retention time'),
      VC('Consecutive blanks', 'No detectable peak in the second blank', '0 peaks above LOD', 'Blank, standard, blank, blank sequence'),
      VC('System suitability', 'All SST criteria pass', 'Per method', 'Run the method SST after corrective action'),
    ],
    escalation: [
      'Carryover persists after wash optimisation, needle/seat replacement and rotor seal replacement.',
      'Onset coincides with a pressure change or a leak at the injector.',
      ...LC_ESCALATION,
    ],
    safety: LC_SAFETY,
    next_questions: [
      'What is the carryover as a percentage of the highest standard, and does it fall with successive blanks?',
      'Which needle wash solvent, volume and cycle count are configured?',
      'Is the autosampler a flow-through-needle or fixed-loop design?',
    ],
  },

  'retention time shift': {
    key: 'retention time shift',
    title: 'Retention time shift or drift',
    hypotheses: [
      H('Mobile phase composition change (evaporation, wrong preparation, pH drift, degradation)', 'high',
        'Prepare fresh mobile phase, re-equilibrate for 10 column volumes and rerun the standard.',
        'Retention times return to the expected values.'),
      H('Flow rate error from pump seals, check valves or air in the pump', 'high',
        'Measure the flow rate gravimetrically or with a flow meter at the detector outlet; purge the pump.',
        'Measured flow deviates by more than 2% from the setpoint, or improves after purging.'),
      H('Column temperature instability or oven not at setpoint', 'medium',
        'Log the oven temperature over a run and compare with the method setpoint.',
        'Temperature variation greater than 1 °C correlates with the drift.'),
      H('Column ageing, contamination or void formation', 'medium',
        'Install a new column of the same type and rerun the standard.',
        'Retention returns to nominal on the new column.'),
      H('Insufficient equilibration between gradient runs', 'medium',
        'Increase post-run equilibration time and compare retention of the first and later injections.',
        'Drift confined to the first injections that resolves with longer equilibration.'),
      H('Dwell volume or gradient proportioning fault', 'low',
        'Run the gradient proportioning valve test (step gradient with UV-absorbing tracer).',
        'Steps deviate from the expected percentage composition.'),
    ],
    checks: [
      'Compare retention times of the SST standard against the method acceptance window and plot drift across the sequence.',
      'Check mobile phase preparation date, bottle levels and whether solvent lines are in the correct bottles.',
      'Verify the pump delivers the set flow rate and the pressure trace is stable without pulsation.',
      'Confirm the column oven is at the method temperature and the column is fully inside the heated zone.',
      'Check column identity, lot and injection count against the method.',
      'Review equilibration time and whether the gradient returns fully to initial conditions.',
      'Check for leaks at fittings between pump and column.',
    ],
    corrective_actions: [
      'Prepare fresh mobile phase with calibrated pH and verified composition; degas.',
      'Purge the pump; replace check valves or seals if flow accuracy fails.',
      'Extend equilibration time and re-run the gradient proportioning test if steps are off.',
      'Replace the column or guard column if a new column restores retention.',
      'Adjust the column oven or thermostat if temperature control fails verification.',
    ],
    verification_criteria: [
      VC('Retention time RSD', '< 0.5% over 6 replicate injections', 'Per method SOP', 'Six replicate injections of the SST standard'),
      VC('Flow rate accuracy', 'Within 2% of setpoint', '±2%', 'Gravimetric measurement over 5 minutes'),
      VC('Column temperature', 'Setpoint ± 1 °C', '±1 °C', 'External probe or oven log over one run'),
    ],
    escalation: ['Flow accuracy fails after seal and check valve replacement.', ...LC_ESCALATION],
    safety: LC_SAFETY,
    next_questions: ['Did the shift affect all peaks equally (flow or temperature) or only some (chemistry)?', 'When was the mobile phase last prepared?'],
  },

  'peak tailing': {
    key: 'peak tailing',
    title: 'Peak tailing',
    hypotheses: [
      H('Secondary interactions with residual silanols (basic analytes at mid pH)', 'high',
        'Inject a neutral marker (e.g. toluene or uracil); compare its symmetry with the analyte.',
        'Neutral marker symmetric while the analyte tails indicates a chemical, not physical, cause.'),
      H('Column inlet frit blockage or column void', 'high',
        'Reverse-flush the column if allowed, or install a new column and compare tailing factor.',
        'Tailing improves on a new column or after flushing.'),
      H('Extra-column volume from long tubing, wrong fittings or a large flow cell', 'medium',
        'Inspect fittings for gaps; shorten tubing; compare tailing with a low-dispersion setup.',
        'Tailing factor improves after reducing extra-column volume.'),
      H('Sample overload or sample solvent stronger than the mobile phase', 'medium',
        'Dilute the sample 10-fold and dissolve in initial mobile phase; reinject.',
        'Tailing factor improves with dilution or a weaker sample solvent.'),
      H('Mobile phase pH close to the analyte pKa or insufficient buffer strength', 'medium',
        'Adjust pH at least 2 units from the pKa or increase buffer concentration and compare.',
        'Symmetry improves with pH or buffer change.'),
    ],
    checks: [
      'Calculate the USP tailing factor for the affected peak and for a neutral marker.',
      'Check whether all peaks tail (physical cause) or only specific analytes (chemical cause).',
      'Inspect fittings at the column inlet and outlet for improper seating.',
      'Compare sample solvent with the initial mobile phase composition.',
      'Review column injection count and last regeneration.',
      'Verify mobile phase pH and buffer concentration against the method.',
    ],
    corrective_actions: [
      'Replace or regenerate the column; install a guard column or inline filter.',
      'Reseat fittings, shorten connecting tubing and use low-dispersion capillaries.',
      'Dilute samples and match the sample solvent to the mobile phase.',
      'Adjust mobile phase pH or buffer strength within the validated method range.',
    ],
    verification_criteria: [
      VC('USP tailing factor', '≤ 1.5 (or per method)', 'Per SST', 'Replicate SST injections'),
      VC('Theoretical plates', '≥ method minimum', 'Per SST', 'Calculate from SST standard'),
    ],
    escalation: LC_ESCALATION,
    safety: LC_SAFETY,
    next_questions: ['What is the current tailing factor and what was it at method validation?', 'Does a neutral marker also tail?'],
  },

  'peak broadening': {
    key: 'peak broadening',
    title: 'Peak broadening or loss of resolution',
    hypotheses: [
      H('Column efficiency loss (contamination, void, stationary phase degradation)', 'high',
        'Install a new column and compare plate count.',
        'Plate count recovers on the new column.'),
      H('Extra-column band broadening from tubing, fittings or detector cell', 'high',
        'Minimise tubing length and internal diameter, check fittings and reduce detector time constant.',
        'Peak width narrows after reducing extra-column volume.'),
      H('Detector settings inappropriate (slow sampling rate or long time constant)', 'medium',
        'Set data rate to give at least 20 points across the narrowest peak and repeat.',
        'Peaks sharpen at the higher data rate.'),
      H('Sample overload or strong sample solvent', 'medium',
        'Dilute sample and dissolve in initial mobile phase.',
        'Peak width decreases with dilution.'),
      H('Temperature or mobile phase composition drift changing selectivity', 'low',
        'Verify oven temperature and mobile phase preparation.',
        'Resolution returns with fresh mobile phase and stable temperature.'),
    ],
    checks: [
      'Calculate plate count and resolution for the critical pair and compare with validation values.',
      'Check whether broadening affects early-eluting peaks most (extra-column effect) or all peaks (column).',
      'Inspect tubing lengths, internal diameters and fitting seating between injector, column and detector.',
      'Confirm detector data rate and time constant match the peak widths.',
      'Review the sample solvent and injection volume.',
    ],
    corrective_actions: [
      'Replace the column or guard column.',
      'Replace connecting tubing with shorter, narrower capillaries and reseat fittings.',
      'Increase detector sampling rate and reduce time constant.',
      'Reduce injection volume or dilute the sample.',
    ],
    verification_criteria: [
      VC('Resolution of critical pair', '≥ 1.5 or per method', 'Per SST', 'SST injection'),
      VC('Theoretical plates', '≥ method minimum', 'Per SST', 'SST injection'),
    ],
    escalation: LC_ESCALATION,
    safety: LC_SAFETY,
    next_questions: ['Which peaks broadened most, early or late eluting?', 'What is the column injection count?'],
  },

  'split peaks': {
    key: 'split peaks',
    title: 'Split or shouldered peaks',
    hypotheses: [
      H('Partially blocked column inlet frit or channelling in the packed bed', 'high',
        'Inject a neutral marker; if it also splits, replace the column or guard.',
        'Splitting disappears on a new column.'),
      H('Sample solvent much stronger than the mobile phase', 'high',
        'Dissolve the sample in initial mobile phase and reinject.',
        'Single symmetric peak.'),
      H('Injection of analyte in two ionic forms (pH near pKa)', 'medium',
        'Buffer the sample and mobile phase at a pH 2 units from the pKa.',
        'Single peak at controlled pH.'),
      H('Co-eluting impurity or isomer', 'medium',
        'Change gradient slope or column chemistry; check peak purity with DAD or MS.',
        'Two distinct compounds resolved or confirmed.'),
    ],
    checks: [
      'Check whether all peaks split (system) or only the analyte (chemistry).',
      'Compare sample solvent with the mobile phase.',
      'Inspect the column inlet and guard for contamination; note pressure trends.',
      'Assess peak purity with DAD spectra or mass spectra across the peak.',
    ],
    corrective_actions: [
      'Replace the guard column or column; add an inline filter.',
      'Match the sample solvent to the mobile phase and reduce injection volume.',
      'Control pH with adequate buffer strength.',
    ],
    verification_criteria: [
      VC('Peak shape', 'Single peak, tailing factor ≤ 1.5', 'Per SST', 'SST injection'),
    ],
    escalation: LC_ESCALATION,
    safety: LC_SAFETY,
    next_questions: ['Do all peaks split or only one?', 'What solvent is the sample dissolved in?'],
  },

  'noisy baseline': {
    key: 'noisy baseline',
    title: 'Noisy baseline',
    hypotheses: [
      H('Air bubbles in pump or detector from inadequate degassing', 'high',
        'Purge the pump and detector flow cell; check the degasser status.',
        'Noise falls after purging.'),
      H('Contaminated or poorly mixed mobile phase (periodic noise at pump stroke frequency)', 'high',
        'Run with premixed mobile phase; compare noise.',
        'Periodic noise disappears with premixed solvent.'),
      H('Detector lamp ageing or dirty flow cell', 'medium',
        'Check lamp hours and intensity; flush the flow cell with a strong solvent.',
        'Lamp energy below specification or noise improves after flushing.'),
      H('Pump seal or check valve wear causing pressure ripple', 'medium',
        'Inspect the pressure trace for ripple greater than 2% and correlate with noise.',
        'Ripple exceeds specification.'),
      H('Electrical interference or ground loop', 'low',
        'Run with the detector connected but no flow; observe noise.',
        'Noise present without flow indicates electrical origin.'),
    ],
    checks: [
      'Measure baseline noise over 10 minutes with the method blank gradient and compare with specification.',
      'Confirm degasser operation and purge all channels.',
      'Inspect the pressure trace for pulsation or ripple.',
      'Check lamp hours and detector self-test results.',
      'Test with premixed mobile phase and with no flow.',
    ],
    corrective_actions: [
      'Degas and purge; replace degasser if it fails self-test.',
      'Prepare fresh mobile phase; premix if proportioning is suspected.',
      'Flush or replace the flow cell; replace the lamp if energy is low.',
      'Replace pump seals or check valves if ripple persists.',
    ],
    verification_criteria: [
      VC('Baseline noise', 'Within detector specification (e.g. < 0.05 mAU peak-to-peak)', 'Per detector spec', '10 min blank at method conditions'),
      VC('Pressure ripple', '< 2% of operating pressure', '±2%', 'Observe pressure trace over 5 min'),
    ],
    escalation: LC_ESCALATION,
    safety: LC_SAFETY,
    next_questions: ['Is the noise periodic (pump) or random (detector or electrical)?', 'When was the lamp last replaced?'],
  },

  'baseline drift': {
    key: 'baseline drift',
    title: 'Baseline drift',
    hypotheses: [
      H('Mobile phase absorbance mismatch between A and B across the gradient', 'high',
        'Run a blank gradient; compare drift with an isocratic hold.',
        'Drift follows the gradient profile.'),
      H('Column temperature or ambient temperature changes (refractive index effects)', 'medium',
        'Log room and oven temperature during the run.',
        'Drift tracks temperature change.'),
      H('Column bleed or slowly eluting contaminants', 'medium',
        'Hold at high organic and watch the baseline; compare with a new column.',
        'Drift reduces on a clean or new column.'),
      H('Detector lamp warming up or ageing', 'low',
        'Allow 30 minutes warm-up and compare; check lamp energy.',
        'Drift disappears after warm-up or lamp replacement.'),
    ],
    checks: [
      'Run a blank gradient and an isocratic hold and compare drift.',
      'Check the mobile phase additive concentrations match in both channels.',
      'Monitor temperature stability of the oven and the room.',
      'Verify detector warm-up time and lamp status.',
    ],
    corrective_actions: [
      'Match additive concentration in both mobile phases; use higher-purity solvents.',
      'Stabilise temperature; use a column thermostat.',
      'Flush or replace the column if bleed is confirmed.',
      'Replace the lamp if energy is low.',
    ],
    verification_criteria: [
      VC('Baseline drift', 'Within detector specification over the run', 'Per spec', 'Blank gradient at method conditions'),
    ],
    escalation: LC_ESCALATION,
    safety: LC_SAFETY,
    next_questions: ['Does the drift follow the gradient or occur under isocratic conditions?'],
  },

  'high backpressure': {
    key: 'high backpressure',
    title: 'High or rising system backpressure',
    hypotheses: [
      H('Blocked column inlet frit or guard column', 'high',
        'Remove the column and measure system pressure with a union; then test the guard alone.',
        'Pressure normal without the column and high with it.'),
      H('Blocked inline filter, frit or capillary', 'high',
        'Disconnect modules stepwise from detector to pump and measure pressure at each stage.',
        'Pressure drops when a specific component is removed.'),
      H('Sample or buffer precipitation in the flow path', 'medium',
        'Check mobile phase miscibility and buffer solubility at the organic content used; flush with water.',
        'Pressure normalises after aqueous flush.'),
      H('Mobile phase viscosity or temperature lower than expected', 'medium',
        'Confirm composition and column temperature; compare with the method pressure record.',
        'Pressure matches expectation when conditions are corrected.'),
      H('Injection valve or needle seat blockage', 'low',
        'Bypass the autosampler and measure pressure.',
        'Pressure drops when the autosampler is bypassed.'),
    ],
    checks: [
      'Record the current pressure at the method flow rate and compare with the validated baseline.',
      'Remove the column and measure system pressure with a union.',
      'Test with and without the guard column and inline filter.',
      'Check mobile phase for precipitate, especially buffers at high organic content.',
      'Confirm column temperature and flow rate setpoints.',
      'Inspect the pressure trace for spikes at injection.',
    ],
    corrective_actions: [
      'Replace the inline filter, guard column or column frit.',
      'Reverse-flush the column only if the manufacturer permits it.',
      'Flush the system with water then organic to remove precipitates.',
      'Replace blocked capillaries or the needle seat.',
      'Filter samples and mobile phases through 0.2 µm membranes.',
    ],
    verification_criteria: [
      VC('System pressure at method flow', 'Within 10% of validated baseline', '±10%', 'Method conditions, column at temperature'),
      VC('Pressure without column', 'Below 10% of column pressure', 'Per system', 'Union in place of column'),
    ],
    escalation: [
      'Pressure remains high with the column removed after filter and capillary replacement.',
      'Pump pressure limit alarms recur or leaks appear.',
      ...LC_ESCALATION,
    ],
    safety: [
      'Never exceed the column or system pressure limits; reduce flow before troubleshooting.',
      ...LC_SAFETY,
    ],
    next_questions: ['What is the pressure with and without the column?', 'Did the rise occur suddenly or gradually?'],
  },

  'low sensitivity': {
    key: 'low sensitivity',
    title: 'Low sensitivity or signal loss',
    hypotheses: [
      H('Sample preparation or dilution error', 'high',
        'Inject a freshly prepared reference standard at known concentration.',
        'Reference standard response is normal.'),
      H('Detector problem: lamp ageing, wrong wavelength, dirty flow cell, or MS source contamination', 'high',
        'Check lamp energy and wavelength; for MS, run the tuning compound and inspect the source.',
        'Lamp or tune values below specification; response recovers after cleaning.'),
      H('Partial injection failure (air in syringe, wrong vial, loop underfill)', 'medium',
        'Inspect the autosampler injection log; run the injection precision test.',
        'Injection RSD exceeds specification or volume error found.'),
      H('Analyte degradation or adsorption in vials, tubing or column', 'medium',
        'Reinject a freshly prepared standard versus an aged one.',
        'Fresh standard response higher than aged.'),
      H('Leak reducing effective flow to the detector', 'low',
        'Inspect for leaks and confirm flow at the detector outlet.',
        'Leak detected or flow below setpoint.'),
    ],
    checks: [
      'Inject a fresh standard and compare peak area with the historical response.',
      'Verify detector settings (wavelength, bandwidth, gain, MS tune) and lamp or source status.',
      'Run the injector precision test (6 replicates) and review the injection log.',
      'Inspect sample preparation records and dilution calculations.',
      'Check for leaks and confirm flow rate at the detector outlet.',
    ],
    corrective_actions: [
      'Replace the lamp or clean the flow cell; clean the MS source if tune fails.',
      'Repair leaks; replace injector seals or syringe.',
      'Re-prepare samples and standards; use silanised vials if adsorption is suspected.',
      'Correct detector settings to the validated method.',
    ],
    verification_criteria: [
      VC('Standard response', 'Within 10% of historical mean area', '±10%', 'Six replicate injections of the reference standard'),
      VC('Injection precision', 'Area RSD < 1%', 'Per method', 'Six replicates'),
    ],
    escalation: LC_ESCALATION,
    safety: LC_SAFETY,
    next_questions: ['Is the loss seen for a freshly prepared standard as well as samples?', 'Did all peaks lose response or only some?'],
  },

  'no peak': {
    key: 'no peak',
    title: 'No peak detected',
    hypotheses: [
      H('No injection occurred (empty vial, wrong vial position, needle not reaching liquid)', 'high',
        'Inspect vial fill level and position; watch an injection cycle; check the injection log.',
        'Vial issue found or injection error logged.'),
      H('Detector not acquiring or set to the wrong wavelength/mass', 'high',
        'Verify detector settings and run a known standard.',
        'Standard detected once settings are corrected.'),
      H('Analyte not eluting within the run (retained or eluting in the void)', 'medium',
        'Extend the run time or gradient and inspect the void volume region.',
        'Peak appears later or in the void.'),
      H('Flow path blocked or leak preventing flow through the column', 'medium',
        'Confirm flow at the detector outlet and check pressure against baseline.',
        'No flow at outlet or pressure abnormal.'),
      H('Sample degradation or absence of analyte', 'low',
        'Inject a certified standard.',
        'Standard detected while the sample is not.'),
    ],
    checks: [
      'Inject a known standard to confirm the system detects the analyte.',
      'Check vial positions, fill levels and the injection log.',
      'Verify detector acquisition settings and that data is being recorded.',
      'Confirm flow and pressure match method values.',
      'Extend the run to rule out late elution.',
    ],
    corrective_actions: [
      'Correct vial placement or fill level; repair the injector if it fails to draw sample.',
      'Set the detector to the validated wavelength or mass and re-run.',
      'Clear the blockage or repair the leak.',
      'Re-prepare the sample and standards.',
    ],
    verification_criteria: [
      VC('Standard detection', 'Peak at expected retention time with expected area', '±10% area', 'Inject reference standard'),
    ],
    escalation: LC_ESCALATION,
    safety: LC_SAFETY,
    next_questions: ['Is a known standard detected?', 'Was an injection actually performed according to the log?'],
  },

  'column overloading': {
    key: 'column overloading',
    title: 'Column overloading',
    hypotheses: [
      H('Mass overload from excessive sample concentration', 'high', 'Inject a 10-fold dilution.', 'Peak shape and retention normalise.'),
      H('Volume overload from large injection in strong solvent', 'high', 'Halve the injection volume and use initial mobile phase as sample solvent.', 'Peak width and fronting reduce.'),
      H('Column capacity reduced by ageing', 'medium', 'Compare with a new column at the same load.', 'New column tolerates the load.'),
    ],
    checks: ['Compare peak shape across a dilution series.', 'Check injection volume against the column dimensions.', 'Review sample solvent strength.'],
    corrective_actions: ['Dilute samples or reduce injection volume.', 'Match sample solvent to mobile phase.', 'Use a larger-diameter or higher-capacity column if the method requires the load.'],
    verification_criteria: [VC('Peak shape', 'Symmetric, tailing factor ≤ 1.5', 'Per SST', 'SST at working concentration')],
    escalation: LC_ESCALATION,
    safety: LC_SAFETY,
    next_questions: ['What mass of analyte is injected per run relative to the column capacity?'],
  },

  'pressure surge at injection': {
    key: 'pressure surge at injection',
    title: 'Pressure surge at injection',
    hypotheses: [
      H('Injection of sample in a solvent immiscible or much more viscous than the mobile phase', 'high', 'Inject the sample solvent alone and watch the pressure trace.', 'Surge reproduced by solvent alone.'),
      H('Injection valve switching fault or worn rotor seal', 'medium', 'Watch the pressure trace during valve switching with a blank injection.', 'Spike present with blank injection.'),
      H('Particulates in sample blocking the needle seat or loop', 'medium', 'Filter or centrifuge samples and reinject.', 'Surge disappears with filtered sample.'),
    ],
    checks: ['Inject sample solvent only.', 'Inject a filtered sample.', 'Inspect the valve and needle seat.'],
    corrective_actions: ['Match sample solvent to the mobile phase.', 'Filter or centrifuge samples.', 'Replace the rotor seal or needle seat.'],
    verification_criteria: [VC('Injection pressure spike', 'Below 5% of operating pressure', '±5%', 'Observe pressure trace across three injections')],
    escalation: LC_ESCALATION,
    safety: LC_SAFETY,
    next_questions: ['What solvent are the samples dissolved in?'],
  },

  'void volume issue': {
    key: 'void volume issue',
    title: 'Void volume or unretained peak issues',
    hypotheses: [
      H('Column void at the inlet from pressure shock or bed collapse', 'high', 'Inject a neutral marker; compare with a new column.', 'Broad or split marker on the old column only.'),
      H('Analyte eluting near the void due to weak retention', 'medium', 'Reduce initial organic content and observe retention.', 'Retention increases.'),
    ],
    checks: ['Measure the void time with an unretained marker.', 'Compare with column certificate values.'],
    corrective_actions: ['Replace the column; avoid pressure shocks (ramp flow).', 'Adjust initial mobile phase strength within the method range.'],
    verification_criteria: [VC('Retention factor of first analyte', 'k ≥ 1', 'Per method', 'SST injection')],
    escalation: LC_ESCALATION,
    safety: LC_SAFETY,
    next_questions: ['What is the retention factor of the affected peak?'],
  },

  'lcms source contamination': {
    key: 'lcms source contamination',
    title: 'LC-MS ion source contamination',
    hypotheses: [
      H('Deposits on the spray shield, capillary or cone from matrix or non-volatile buffers', 'high',
        'Inspect the source; run the tuning compound and compare with the last passing tune.',
        'Visible deposits; sensitivity recovers after cleaning.'),
      H('Non-volatile mobile phase additives or high salt samples', 'medium',
        'Review mobile phase additives and sample cleanup.',
        'Non-volatile buffer or unextracted matrix identified.'),
      H('Capillary or nebuliser partially blocked', 'medium',
        'Inspect spray stability visually and check spray current.',
        'Unstable spray or abnormal current.'),
    ],
    checks: [
      'Run the tune or calibration check and compare with the last passing result.',
      'Visually inspect the spray shield, capillary entrance and cone for deposits.',
      'Review mobile phase additives for MS compatibility.',
      'Check divert valve timing so that the salt front goes to waste.',
    ],
    corrective_actions: [
      'Clean the source components per the manufacturer procedure (operator-level parts only).',
      'Replace non-volatile buffers with volatile equivalents from the validated method.',
      'Improve sample cleanup and use the divert valve for the void.',
      'Replace the capillary or nebuliser needle if blocked.',
    ],
    verification_criteria: [
      VC('Tune compound response', 'Within manufacturer specification', 'Per instrument', 'Run autotune or check tune'),
      VC('Standard response', 'Within 20% of historical mean', '±20%', 'Inject reference standard'),
    ],
    escalation: ['Sensitivity remains low after source cleaning and tune.', 'Any action inside the vacuum region or heated zones.', ...LC_ESCALATION],
    safety: ['Allow heated source components to cool before handling; use gloves and avoid touching optics.', ...LC_SAFETY],
    next_questions: ['When was the source last cleaned and did the tune pass afterwards?'],
  },

  'ion suppression': {
    key: 'ion suppression',
    title: 'Ion suppression or matrix effect',
    hypotheses: [
      H('Co-eluting matrix components (phospholipids, salts) suppressing ionisation', 'high',
        'Post-column infusion of analyte while injecting blank matrix extract; and matrix factor from post-extraction spike vs neat standard.',
        'Signal dip at the analyte retention time; matrix factor outside 0.85–1.15 with unacceptable RSD.'),
      H('Insufficient sample cleanup for the matrix', 'high',
        'Compare matrix factor across cleanup methods (protein precipitation vs SPE vs LLE).',
        'Matrix factor improves with stronger cleanup.'),
      H('Chromatographic co-elution with the matrix front', 'medium',
        'Increase retention or modify the gradient to move the analyte away from the suppression zone.',
        'Suppression reduced after retention shift.'),
      H('Source contamination mimicking suppression (high background)', 'low',
        'Distinguish high TIC noise from suppression with the infusion experiment.',
        'Infusion shows no dip but the background is elevated.'),
    ],
    checks: [
      'Perform the post-column infusion experiment to locate suppression zones.',
      'Calculate the matrix factor (ICH M10 approach) in at least six matrix lots.',
      'Check whether a stable isotope labelled internal standard tracks the suppression.',
      'Review sample cleanup and the gradient relative to the matrix front.',
    ],
    corrective_actions: [
      'Improve cleanup (SPE, LLE or phospholipid removal) within the validated approach.',
      'Adjust chromatography to separate the analyte from the suppression zone.',
      'Use a stable isotope labelled internal standard.',
      'Dilute the extract if sensitivity allows.',
    ],
    verification_criteria: [
      VC('IS-normalised matrix factor RSD', '≤ 15% across 6 lots', 'Per ICH M10', 'Post-extraction spike vs neat'),
      VC('Accuracy and precision in matrix', 'Within ±15% (±20% at LLOQ)', 'Per ICH M10', 'QC samples in matrix'),
    ],
    escalation: LC_ESCALATION,
    safety: LC_SAFETY,
    next_questions: ['What is the measured matrix factor and does it vary between lots?', 'Which sample cleanup is used?'],
  },

  'adduct formation': {
    key: 'adduct formation',
    title: 'Unexpected adducts in MS',
    hypotheses: [
      H('Sodium or potassium from glassware, buffers or sample matrix', 'high', 'Use polypropylene vials and freshly prepared mobile phase; compare adduct ratio.', 'Adduct fraction falls.'),
      H('Ammonium or formate adducts from mobile phase additives', 'medium', 'Adjust additive concentration and cone/fragmentor voltage.', 'Protonated molecule dominates.'),
      H('In-source conditions favouring adducts (low fragmentor or cone voltage)', 'medium', 'Increase fragmentor or cone voltage in steps.', 'Adduct intensity decreases relative to [M+H]+.'),
    ],
    checks: ['Identify adduct masses (+22 Na, +38 K, +17 NH4, +45 formate).', 'Review container materials and buffer sources.', 'Check source voltages against the tune report.'],
    corrective_actions: ['Eliminate glass containers and reduce salt sources.', 'Optimise additive concentration and source voltages within the validated method.', 'Quantify on the dominant, stable ion or sum adducts if validated.'],
    verification_criteria: [VC('Adduct to [M+H]+ ratio', 'Stable and below method limit', '±10%', 'Six replicate injections')],
    escalation: LC_ESCALATION,
    safety: LC_SAFETY,
    next_questions: ['Which adduct masses are observed and at what ratio to the protonated molecule?'],
  },

  'instrument communication fault': {
    key: 'instrument communication fault',
    title: 'Instrument communication or error-code fault',
    hypotheses: [
      H('Data system to instrument link lost (LAN or USB, IP conflict, driver)', 'high',
        'Ping the instrument IP or check the device manager; power-cycle the module and the PC.',
        'Communication restores after power cycle or IP correction.'),
      H('Module firmware hang', 'medium', 'Perform a full power cycle of all modules in the manufacturer order.', 'Error clears and modules reconnect.'),
      H('Genuine hardware fault indicated by the error code', 'medium', 'Look up the error code in the manufacturer manual and check the module status LEDs.', 'Code maps to a hardware condition (vacuum, leak, temperature).'),
    ],
    checks: [
      'Record the exact error code and timestamp from the instrument log.',
      'Check cables, network switches and IP configuration.',
      'Power-cycle modules and the data system in the documented sequence.',
      'Check module status LEDs and the vacuum, leak or temperature panels.',
    ],
    corrective_actions: [
      'Reconnect or replace communication cables; assign a static IP.',
      'Reinstall or update the instrument driver.',
      'Disable USB selective suspend on the acquisition PC.',
      'Follow the manual procedure for the specific error code.',
    ],
    verification_criteria: [VC('Instrument status', 'All modules ready, no errors for one full sequence', 'None', 'Run a blank sequence')],
    escalation: ['Error recurs after power cycle and cable checks.', 'Error code indicates vacuum, high-voltage or leak conditions.', ...LC_ESCALATION],
    safety: ['Do not open modules to reseat boards; electrical hazards are present.', ...LC_SAFETY],
    next_questions: ['What is the exact error code and does it clear after a power cycle?'],
  },

  'ic suppressor failure': {
    key: 'ic suppressor failure',
    title: 'Ion chromatography suppressor failure',
    hypotheses: [
      H('Suppressor membrane fouled or exhausted', 'high', 'Check background conductivity and suppressor voltage/current.', 'Background above specification; voltage at limit.'),
      H('Incorrect suppressor current for the eluent concentration', 'medium', 'Recalculate current from eluent concentration and flow.', 'Setting differs from the calculated value.'),
      H('Regenerant flow interrupted (waste line blocked or pump off)', 'medium', 'Check regenerant flow and waste line.', 'Flow absent or blocked.'),
    ],
    checks: ['Record background conductivity and compare with the method value.', 'Verify suppressor current setting.', 'Check regenerant flow path.'],
    corrective_actions: ['Regenerate or replace the suppressor per manufacturer procedure.', 'Set the correct current.', 'Clear the waste line and restore regenerant flow.'],
    verification_criteria: [VC('Background conductivity', 'Within method specification (e.g. < 2 µS/cm for hydroxide eluent)', 'Per method', 'Equilibrated blank run')],
    escalation: LC_ESCALATION,
    safety: LC_SAFETY,
    next_questions: ['What is the current background conductivity and suppressor voltage?'],
  },

  'ic baseline drift': {
    key: 'ic baseline drift',
    title: 'Ion chromatography baseline drift or rise',
    hypotheses: [
      H('Eluent contamination or carbonate uptake in hydroxide eluent', 'high', 'Prepare fresh eluent under nitrogen or use the eluent generator; compare.', 'Drift disappears with fresh eluent.'),
      H('Suppressor not fully equilibrated or degrading', 'medium', 'Allow extended equilibration; check background trend.', 'Background stabilises or continues rising.'),
      H('Temperature fluctuation of the conductivity cell', 'low', 'Check cell temperature stability.', 'Drift tracks temperature.'),
    ],
    checks: ['Trend the background conductivity over 30 minutes.', 'Check eluent preparation and carbonate protection.', 'Verify cell and column temperature.'],
    corrective_actions: ['Prepare fresh eluent; protect from CO2.', 'Regenerate or replace the suppressor.', 'Stabilise temperature.'],
    verification_criteria: [VC('Baseline drift', 'Within method specification over the run', 'Per method', 'Blank run')],
    escalation: LC_ESCALATION,
    safety: LC_SAFETY,
    next_questions: ['Is the eluent generated online or prepared manually?'],
  },
};

// Additional keys that map to the same procedures
LC_ISSUE_PROCEDURES['ic baseline rise'] = LC_ISSUE_PROCEDURES['ic baseline drift'];
LC_ISSUE_PROCEDURES['ic peak distortion'] = LC_ISSUE_PROCEDURES['peak tailing'];
LC_ISSUE_PROCEDURES['ic wrong retention time'] = LC_ISSUE_PROCEDURES['retention time shift'];
LC_ISSUE_PROCEDURES['uhplc high backpressure'] = LC_ISSUE_PROCEDURES['high backpressure'];
LC_ISSUE_PROCEDURES['preplc high backpressure'] = LC_ISSUE_PROCEDURES['high backpressure'];
LC_ISSUE_PROCEDURES['loss of resolution'] = LC_ISSUE_PROCEDURES['peak broadening'];

export const LC_DEFAULT: GenericProcedure = {
  key: 'lc-default',
  title: 'General liquid chromatography troubleshooting',
  hypotheses: [
    H('Mobile phase or sample preparation change', 'medium', 'Prepare fresh mobile phase and standards; rerun the SST.', 'SST passes with fresh preparations.'),
    H('Column performance degradation', 'medium', 'Install a new column of the same type and rerun the SST.', 'SST passes on the new column.'),
    H('Pump, injector or detector hardware fault', 'medium', 'Run the module self-tests and compare flow, injection precision and lamp status with specification.', 'A specific module fails its test.'),
    H('Method parameter deviation (temperature, flow, wavelength, gradient)', 'low', 'Compare the running method line by line against the validated method.', 'A parameter differs.'),
  ],
  checks: [
    'Run the method system suitability test and record every parameter against acceptance criteria.',
    'Compare the current chromatogram with a reference chromatogram from method validation.',
    'Verify mobile phase preparation, degassing and bottle assignment.',
    'Check pressure at method flow against the historical baseline.',
    'Run pump, injector and detector self-tests.',
    'Review the instrument log for errors and recent maintenance.',
  ],
  corrective_actions: [
    'Prepare fresh mobile phase and standards.',
    'Replace guard column or column if SST fails on column parameters.',
    'Service the module that fails its self-test (seals, lamp, needle).',
    'Restore the validated method parameters.',
  ],
  verification_criteria: [
    VC('System suitability', 'All criteria pass', 'Per method', 'SST run after corrective action'),
    VC('Retention time RSD', '< 0.5%', 'Per method', 'Six replicate injections'),
  ],
  escalation: LC_ESCALATION,
  safety: LC_SAFETY,
  next_questions: ['Which SST parameter fails?', 'What changed most recently: mobile phase, column, sample or hardware?'],
};
