#!/usr/bin/env bash
# Concatenates the migrations the documentation agent needs, in dependency order,
# into one file you can paste into the Supabase SQL editor.
#
#   bash scripts/build-bootstrap-sql.sh > bootstrap.sql
#
# Order matters: 019 references sources (001), 020 references documents (019),
# 021 widens a constraint created in 002, and 022 adds documents.ingested_at
# plus the document_chunk_counts view. Every migration is idempotent
# (create table if not exists / drop constraint if exists), so re-running is safe.
#
# This concatenates the real migration files rather than duplicating their SQL,
# so it cannot drift from them.
set -euo pipefail

cd "$(dirname "$0")/../supabase/migrations"

MIGRATIONS=(
  001_sources
  002_knowledge_items
  007_source_refresh_runs
  009_agent_runs
  017_kb_fulltext
  019_documents
  020_document_chunks
  021_widen_technique_check
  022_documents_ingested_at
)

echo "-- LabPulse: schema required by the vendor documentation agent."
echo "-- Generated by scripts/build-bootstrap-sql.sh — do not edit by hand."
echo "begin;"
echo

for m in "${MIGRATIONS[@]}"; do
  if [[ ! -f "$m.sql" ]]; then
    echo "missing migration: $m.sql" >&2
    exit 1
  fi
  echo "-- ===================== $m.sql ====================="
  cat "$m.sql"
  echo
done

echo "commit;"
